### ISSUE TITLE
Please put up an .app or a how-to-compile

### ISSUE THREAD

**Issue by FelixAkk** [kalleboo/PingMenu#1]
Hi,

This is pretty much exactly what I was looking for, but could you put up a recently compiled version or a guide on how to compile? Thanks in advance!

**Comment by kalleboo** [comment]
There used to be one, but GitHub removed the downloads feature so it disappeared. Here you go: http://kalleboo.s3.amazonaws.com/github/PingMenu.app.zip (Not codesigned, so right-click-open on the unzipped app)

**Comment by FelixAkk** [comment]
Superb! Thanks a lot! :)
