### ISSUE TITLE
Endless ping counter after 2^16 pings

### ISSUE THREAD

**Issue by psarossy** [kalleboo/PingMenu#11]
When the ping sequence counter reaches 65536, the ping turns into an endless timeout line (it will just keep counting "forever").

**Comment by kalleboo** [comment]
This should have been fixed a couple months ago (d9fe1baff18cba2961718a0ea0fdcb50ad0b2474), can you confirm this is happening with the latest version as well?

**Comment by psarossy** [comment]
Installed the latest version, I presume I had an outdated one. I'll report back if it's working as intended if it gets that high again.

There is no indication of the revision in the app, may worth adding that (in the preferences maybe)? I think having the build number at least would already help to determine what version is installed.
