### ISSUE TITLE
font-color in OS X 10.10 Yosemite with dark status bar

### ISSUE THREAD

**Issue by mrflix** [kalleboo/PingMenu#12]
Your tool is great. Thanks for building it!!
I just installed OS X Yosemite and was looking forward to switch to the dark status bar. Unfortunately some tools I use don't support the dark background yet – one of them being PingMenu:
![screen shot 2014-10-21 at 06 22 17](https://cloud.githubusercontent.com/assets/60777/4713088/1c3a40e6-58da-11e4-9b13-fdc4f7ae8901.png)
I read about how to detect darkMode on stackoverflow: http://stackoverflow.com/questions/25379525/how-to-detect-dark-mode-in-yosemite-to-change-the-status-bar-menu-icon
Does anyone have sufficient Objectiv-C knowledge to implement a font-color change?

**Comment by kalleboo** [comment]
Done 0d5f051f8f463054007c7e6d3fdee329b9ff9dd4

**Comment by mrflix** [comment]
Sweet! Thanks a ton Karl!
![screen shot 2014-10-22 at 12 57 03](https://cloud.githubusercontent.com/assets/60777/4734950/3e39f802-59da-11e4-91c9-69635412b4eb.png)
