### ISSUE TITLE
Latest request time

### ISSUE THREAD

**Issue by FelixAkk** [kalleboo/PingMenu#2]
Hi, love the utility!

Was hoping to tinker with it some myself soon too, but untill then, perhaps you can quickly plug this in: could you make the dropdown menu display when the last request was made (e.g. 3s ago, 4s ago ... 1m25s ago). Right now it seems like it's stuck when there is no connection because it keeps displaying the info of the latest request number, while I suspect that it keeps checking but doesn't show a new number as long as nothing changes (e.g. it keeps getting no route to host)?

**Comment by kalleboo** [comment]
Sure, sounds like a good idea, when I get a bit more free time later this week I'll implement it. Meanwhile try the latest version which changes the menu to "(no route)" or "(dns error)" when the connection fails, which should help with the root of your issue.

**Comment by kalleboo** [comment]
Fixed in 1.1, which adds a list of info for the latest 10 pings.
