### ISSUE TITLE
65535th ping takes forever

### ISSUE THREAD

**Issue by fenhl** [kalleboo/PingMenu#4]
The ping with the number `#65535` (which occurs after leaving the app running for 3 days and 19 hours) takes forever, and a ping `#65536` is never started. This is annoying if you keep the app running in the background continuously.

**Comment by kalleboo** [comment]
I was actually being annoyed by this issue myself just last week and had a fix in the works :) Completed and tested it today, here you go: https://github.com/kalleboo/PingMenu/raw/master/PingMenu.app.zip
